// Готовые бойцы из артефакта «UFC Бойцы»: ростер игры, топ-15 дивизионов, малые лиги, легенды и гориллы.
// Имена — те, что стоят в артефакте по умолчанию (изменённые, не настоящие). Файл сгенерирован из данных
// артефакта; внешность реальных ростеров лежит в ROSTER_LOOKS, у остальных её подбирает fighters.js
// по стране и стилю (детерминированно от id, так что боец всегда выглядит одинаково).
//
// Запись: [id, имя, прозвище, страна, стиль, левша(0/1), рост (м), мастерство 0..100, дивизион, группа, ранг]
//   дивизион: 'fw' | 'lw' | 'ww' | 'hw'
//   группа:   'ufc' | 'cw' | 'aca' | 'pfl' | 'legend' | 'orig' | 'gorilla' | 'boss'
//   ранг:     0 — чемпион, 1..15 — место в рейтинге, null — вне рейтинга
export const FIGHTER_ROWS = [
  ["volkanovski","Алекс Волканов","Грейт","AU","boxer",0,1.68,87,"fw","ufc",0],
  ["gaethje","Джастин Гэтли","Хайлайт","US","brawler",0,1.8,82,"lw","ufc",0],
  ["holloway","Макс Холлидэй","Блессед","US","boxer",0,1.8,88,"fw","ufc",4],
  ["oliveira","Шарлез Оливейр","Бронкс","BR","kickboxer",0,1.78,81,"lw","ufc",3],
  ["topuria","Илия Топур","Матадор","ES","boxer",0,1.7,87,"fw","ufc",1],
  ["makhachev","Ислам Мактаев","Орёл гор","RU","brawler",1,1.78,87,"lw","ufc",0],
  ["tsarukyan","Арман Царунц","Ахалкалаки","AM","brawler",0,1.7,84,"lw","ufc",2],
  ["poirier","Дастин Пуарен","Диамант","US","boxer",1,1.75,83,"lw","legend",null],
  ["aldo","Жозе Алдейру","Жуниор","BR","kickboxer",0,1.7,88,"fw","legend",null],
  ["mcgregor","Конор Макгрен","Ноториус","IE","boxer",1,1.75,83,"lw","legend",null],
  ["buran","Тимур Жаксылыков","Буран","KZ","boxer",0,1.78,77,"lw","orig",null],
  ["bear","Руслан Каримбеков","Медведь","RU","brawler",0,1.91,68,"hw","orig",null],
  ["evloev","Мовсар Евлаев","Тихий","RU","wrestler",0,1.7,84,"fw","ufc",1],
  ["lopes","Диего Лопеш","Лобо","BR","brawler",0,1.75,84,"fw","ufc",2],
  ["murphy","Лерой Мэрфи","Ловкач","GB","boxer",0,1.75,83,"fw","ufc",3],
  ["sterling","Алджамен Стерлинг","Фанк","US","wrestler",0,1.75,82,"fw","ufc",4],
  ["silva","Жан Сильва-Нети","Бомбардир","BR","brawler",0,1.68,82,"fw","ufc",5],
  ["allen","Арни Эллен","Всевышний","GB","boxer",0,1.78,81,"fw","ufc",6],
  ["sabatini","Пэт Сабатино","Пэт","US","wrestler",0,1.7,79,"fw","ufc",7],
  ["andrusca","Павел Андрусик","Молдаванин","MD","brawler",0,1.7,78,"fw","ufc",8],
  ["zalal","Юсеф Заляль","Самум","MA","kickboxer",1,1.73,78,"fw","ufc",9],
  ["vallejos","Кевин Вальехо","Аргентинец","AR","brawler",0,1.7,78,"fw","ufc",10],
  ["brito","Жоандерсон Бритту","Бритто","BR","wrestler",0,1.68,77,"fw","ufc",11],
  ["costa","Мелькизаэл Косте","Мэл","BR","boxer",0,1.72,77,"fw","ufc",12],
  ["garcia","Стив Гарсиа","Гарс","US","kickboxer",0,1.8,77,"fw","ufc",13],
  ["pico","Аарон Пикко","Пик","US","boxer",0,1.7,78,"fw","ufc",14],
  ["emmers","Джамалл Эммерт","Эм","US","wrestler",0,1.75,76,"fw","ufc",15],
  ["pimblett","Падди Пимлетт","Малыш","GB","kickboxer",0,1.78,80,"lw","ufc",5],
  ["salkilld","Калиан Сакилит","Тихоня","AU","boxer",0,1.8,80,"lw","ufc",6],
  ["saintdenis","Бенуа Сен-Дюнь","Бульдог","FR","brawler",0,1.78,80,"lw","ufc",7],
  ["moicano","Ренато Мойсано","Зомби","BR","boxer",0,1.78,80,"lw","ufc",8],
  ["gamrot","Матеуш Гомрот","Гром","PL","wrestler",0,1.75,80,"lw","ufc",9],
  ["ruffy","Маурисио Раффи","Мозг","BR","kickboxer",1,1.8,80,"lw","ufc",10],
  ["nolan","Том Ноулан","Нол","AU","boxer",0,1.8,78,"lw","ufc",11],
  ["fiziev","Рафаэль Физаев","Молот","KG","kickboxer",0,1.77,80,"lw","ufc",12],
  ["musayev","Тофик Мусайев","Тофик","AZ","wrestler",0,1.76,78,"lw","ufc",13],
  ["dawson","Грант Даусон","Каменщик","US","wrestler",0,1.75,77,"lw","ufc",14],
  ["turner","Джейлин Тернер","Жираф","US","brawler",0,1.93,78,"lw","ufc",15],
  ["prates","Карлос Пратиш","Корона","BR","kickboxer",0,1.88,83,"ww","ufc",1],
  ["garry","Иан Мачадо Гэрри","Сэр Свэг","IE","kickboxer",0,1.85,82,"ww","ufc",2],
  ["morales","Майкл Мораль","Хитрец","EC","boxer",0,1.85,82,"ww","ufc",3],
  ["dellam","Джек Делла-Мадена","Стальной","AU","boxer",0,1.82,85,"ww","ufc",4],
  ["brady","Шон Брэйдли","Шейки","US","wrestler",0,1.75,81,"ww","ufc",5],
  ["bonfim","Габриэл Бонфин","Мастер","BR","wrestler",0,1.83,78,"ww","ufc",6],
  ["belal","Билал Мухамед","Мемфис","US","wrestler",0,1.8,80,"ww","ufc",7],
  ["buckley","Джоаким Баклер","Хулиган","US","brawler",0,1.8,80,"ww","ufc",8],
  ["medic","Урош Медиц","Серб","RS","kickboxer",0,1.8,78,"ww","ufc",9],
  ["edwards","Лион Эдвардс","Рокстар","GB","boxer",0,1.82,82,"ww","ufc",10],
  ["malott","Майк Малот","Малыш","CA","boxer",0,1.83,78,"ww","ufc",11],
  ["usman","Камару Осман","Кошмар","NG","wrestler",0,1.83,80,"ww","ufc",12],
  ["amosov","Ярослав Амосин","Борец","UA","wrestler",0,1.8,78,"ww","ufc",13],
  ["holland","Кевин Холлен","Тренер","US","brawler",0,1.93,78,"ww","ufc",14],
  ["drodrig","Дэниел Родригес","Дэнни","US","boxer",0,1.8,77,"ww","ufc",15],
  ["aspinal","Томас Эспиналл","Король","GB","boxer",0,1.96,88,"hw","ufc",0],
  ["gaine","Сирил Гейн","Хороший парень","FR","kickboxer",1,1.93,86,"hw","ufc",1],
  ["volgin","Александр Волгин","Драго","RU","kickboxer",0,1.99,84,"hw","ufc",2],
  ["pavlovsky","Сергей Павловский","Тигр","RU","brawler",0,1.91,85,"hw","ufc",3],
  ["blade","Кертис Блэйд","Разрушитель","US","wrestler",0,1.93,83,"hw","ufc",4],
  ["almeyda","Жайлтон Альмейда","Платок","BR","wrestler",0,1.88,84,"hw","ufc",5],
  ["cortes","Вальдо Кортес-Акоста","Пуэрториканец","DO","brawler",0,1.91,82,"hw","ufc",6],
  ["spivakov","Сергей Спиваков","Молдаванин","MD","wrestler",0,1.91,80,"hw","ufc",7],
  ["tybur","Марцин Тыбура","Тайбор","PL","brawler",0,1.91,78,"hw","ufc",8],
  ["lewiston","Дэррик Льюистон","Чёрный зверь","US","brawler",0,1.91,80,"hw","ufc",9],
  ["teixeira","Таллисон Тейшейра","Дровосек","BR","boxer",0,1.93,79,"hw","ufc",10],
  ["diniz","Жонатас Динис","Пантера","BR","brawler",0,1.88,79,"hw","ufc",11],
  ["kunilov","Ризван Кунилов","Рэмбо","RU","kickboxer",0,1.91,78,"hw","ufc",12],
  ["gasimov","Шамиль Гасимов","Кузнец","RU","wrestler",0,1.88,78,"hw","ufc",13],
  ["parkinson","Мик Паркинсон","Гигант","AU","kickboxer",0,1.96,76,"hw","ufc",14],
  ["delich","Анте Делич","Хорват","HR","brawler",0,1.96,76,"hw","ufc",15],
  ["hoston","Росс Хьюстер","Тихоня","GB","boxer",0,1.7,72,"fw","cw",0],
  ["vucen","Джордан Вученик","Серб","GB","brawler",0,1.72,71,"fw","cw",1],
  ["duques","Том Дюкенуа","Дуки","FR","kickboxer",0,1.7,70,"fw","cw",2],
  ["hamm","Ли Хэммонд","Молот","GB","wrestler",0,1.73,69,"fw","cw",3],
  ["williamz","Карл Уильямсон","Кальмар","GB","brawler",1,1.74,68,"fw","cw",4],
  ["maguir","Киран Магвайер","Кабан","IE","brawler",0,1.76,72,"lw","cw",0],
  ["lindq","Оскар Линдквист","Викинг","SE","kickboxer",0,1.8,71,"lw","cw",1],
  ["mazur","Мацей Мазур","Каток","PL","boxer",0,1.78,70,"lw","cw",2],
  ["beridze","Леван Беридзе","Грузин","GE","wrestler",0,1.76,69,"lw","cw",3],
  ["okafor","Тунде Окафор","Тунде","NG","brawler",0,1.8,68,"lw","cw",4],
  ["dunne","Рори Данн","Данни","IE","boxer",0,1.82,73,"ww","cw",0],
  ["kowal","Кацпер Ковальчик","Кузнец","PL","brawler",0,1.84,72,"ww","cw",1],
  ["hollm","Виктор Хольмгрен","Лось","SE","wrestler",0,1.85,71,"ww","cw",2],
  ["marsh","Матис Маршан","Эйфель","FR","kickboxer",1,1.83,70,"ww","cw",3],
  ["whit","Джейк Уитакер","Дикарь","AU","brawler",0,1.82,69,"ww","cw",4],
  ["abdur","Салах Абдурахманов","Борец","RU","wrestler",0,1.68,74,"fw","aca",0],
  ["vagaev","Абубакар Вагаев","Волк","RU","boxer",0,1.7,73,"fw","aca",1],
  ["ulanb","Тагир Уланбеков","Орёл","RU","kickboxer",0,1.72,72,"fw","aca",2],
  ["aliev","Руслан Алиев","Алый","RU","brawler",1,1.69,71,"fw","aca",3],
  ["kerim","Керим Адилов","Ястреб","KZ","wrestler",0,1.71,70,"fw","aca",4],
  ["zhamal","Салман Жамалдинов","Чёрный","RU","brawler",0,1.76,75,"lw","aca",0],
  ["sulei","Алихан Сулейманов","Алик","RU","boxer",0,1.77,74,"lw","aca",1],
  ["kokov","Мухамед Коков","Кок","RU","kickboxer",0,1.78,73,"lw","aca",2],
  ["frol","Артём Фролов","Фрол","RU","boxer",0,1.79,72,"lw","aca",3],
  ["sakhab","Бахтияр Сахабутдинов","Бахти","KZ","wrestler",0,1.77,70,"lw","aca",4],
  ["bagov","Али Багов","Багор","RU","kickboxer",0,1.82,75,"ww","aca",0],
  ["salih","Муслим Салихов","Муса","RU","kickboxer",0,1.8,74,"ww","aca",1],
  ["tumen","Альберт Туменов","Тумен","RU","brawler",0,1.8,73,"ww","aca",2],
  ["podma","Александр Подмаскин","Подма","RU","wrestler",0,1.84,72,"ww","aca",3],
  ["dauk","Ибрагим Даулетмуратов","Дайк","KZ","boxer",0,1.83,70,"ww","aca",4],
  ["rabad","Гаджи Рабаданин","Чемпион","RU","wrestler",0,1.7,78,"fw","pfl",0],
  ["hughs","Пол Хьюс","Хьюзи","GB","boxer",0,1.73,76,"fw","pfl",1],
  ["mckee","Эй-Джей Маккей","Эйджей","US","brawler",0,1.73,77,"fw","pfl",2],
  ["pinedo","Хесус Пинедо","Хес","MX","boxer",0,1.72,74,"fw","pfl",3],
  ["davis","Элфи Дэвидс","Элфи","GB","kickboxer",0,1.7,73,"fw","pfl",4],
  ["nurma","Усман Нурмаев","Хан","RU","wrestler",0,1.78,79,"lw","pfl",0],
  ["sy","Садибу Сай","Сай","FR","kickboxer",0,1.8,76,"lw","pfl",1],
  ["collard","Клэй Коллинз","Бык","US","brawler",0,1.75,75,"lw","pfl",2],
  ["antig","Гаджимурад Антигулин","Гаджи","RU","wrestler",0,1.76,75,"lw","pfl",3],
  ["barna","Мансур Барнави","Мансур","FR","kickboxer",0,1.8,73,"lw","pfl",4],
  ["jacks","Джейсон Джексонс","Джейк","US","brawler",0,1.8,78,"ww","pfl",0],
  ["musae","Шамиль Мусеев","Муса","RU","boxer",0,1.82,77,"ww","pfl",1],
  ["impa","Импа Касангани","Импа","US","kickboxer",0,1.88,76,"ww","pfl",2],
  ["umalat","Магомед Умалатин","Маги","RU","wrestler",0,1.78,75,"ww","pfl",3],
  ["bruno","Давид Реймонд","Ночь","FR","boxer",0,1.84,74,"ww","pfl",4],
  ["gsp","Жорж Сен-Пьер","Рашад","CA","wrestler",0,1.78,86,"ww","legend",null],
  ["khabib","Хабиб Нурмаев","Орёл","RU","wrestler",0,1.78,86,"lw","legend",null],
  ["dj","Деметриус Джонсон","Мистер","US","boxer",0,1.62,86,"fw","legend",null],
  ["faber","Юрайя Фабер","Калифорнийец","US","wrestler",0,1.69,86,"fw","legend",null],
  ["edgar","Фрэнки Эдгар","Крепыш","US","wrestler",0,1.67,86,"fw","legend",null],
  ["diaz","Нейт Диас","Стоктон","US","boxer",0,1.83,86,"ww","legend",null],
  ["ferguson","Тони Фергюсон","Эль Кукуй","US","brawler",0,1.8,86,"lw","legend",null],
  ["lawler","Роби Лоулер","Крутой","US","brawler",1,1.8,86,"ww","legend",null],
  ["hughes","Мэтт Хьюз","Фермер","US","wrestler",0,1.75,86,"ww","legend",null],
  ["penn","Би-Джей Пенн","Малыш","US","boxer",0,1.7,86,"lw","legend",null],
  ["gor1","Гор Громадян","Горилла","AM","brawler",0,1.93,95,"ww","gorilla",null],
  ["gor2","Мбонго Колосс","Король джунглей","NG","brawler",0,1.88,95,"lw","gorilla",null],
  ["gor3","Кинг Брутов","Серебряная спина","RU","brawler",0,1.8,95,"fw","gorilla",null],
  ["gor4","Конго Титан","Альфа","NG","brawler",0,1.96,95,"ww","boss",null],
];

// Внешность бойцов ростера: hs — причёска, shorts/trim — цвета формы, build — телосложение 0.6..0.95.
export const ROSTER_LOOKS = {
  volkanovski: { skin: "#e2b594", hair: "#2a1e16", hs: "buzz", beard: "stubble", shorts: "#1b2f63", trim: "#d8b24a", tattoo: 5, build: 0.9, eye: "#3b2a1a" },
  gaethje: { skin: "#e6bd9c", hair: "#5a4632", hs: "buzz", beard: "goatee", shorts: "#7c0d13", trim: "#eeeeee", tattoo: 0, build: 0.85, eye: "#3b5a6e" },
  holloway: { skin: "#b98363", hair: "#120c08", hs: "fade", beard: "short", shorts: "#111113", trim: "#d8b24a", tattoo: 2, build: 0.72, eye: "#24160c" },
  oliveira: { skin: "#c28d69", hair: "#140e0a", hs: "curly", beard: "stubble", shorts: "#0d5a3b", trim: "#d8b24a", tattoo: 9, build: 0.62, eye: "#24160c" },
  topuria: { skin: "#d9a784", hair: "#15100b", hs: "slick", beard: "short", shorts: "#b3121b", trim: "#d8b24a", tattoo: 4, build: 0.95, eye: "#24160c" },
  makhachev: { skin: "#dcb088", hair: "#19110b", hs: "buzz", beard: "full", shorts: "#1c1c1c", trim: "#2f7d3a", tattoo: 0, build: 0.8, eye: "#2a1b10" },
  tsarukyan: { skin: "#d8a882", hair: "#120c08", hs: "short", beard: "full", shorts: "#d8b24a", trim: "#111111", tattoo: 0, build: 0.92, eye: "#24160c" },
  poirier: { skin: "#e2b594", hair: "#2b1d14", hs: "buzz", beard: "full", shorts: "#18386a", trim: "#eeeeee", tattoo: 6, build: 0.78, eye: "#3b2a1a" },
  aldo: { skin: "#c49270", hair: "#120c08", hs: "short", beard: "stubble", shorts: "#0b7a3e", trim: "#f1c40f", tattoo: 0, build: 0.84, eye: "#24160c" },
  mcgregor: { skin: "#eec5a6", hair: "#4e2c16", hs: "slick", beard: "thick", shorts: "#14161a", trim: "#1f8a4c", tattoo: 7, build: 0.8, eye: "#3b5a6e" },
  buran: { skin: "#d6a57c", hair: "#15100b", hs: "fade", beard: "stubble", shorts: "#18386a", trim: "#d8b24a", tattoo: 0, build: 0.72, eye: "#24160c" },
  bear: { skin: "#dcb088", hair: "#19110b", hs: "bald", beard: "thick", shorts: "#1c1c1c", trim: "#c8101a", tattoo: 0, build: 0.6, eye: "#2a1b10" },
};
